"""Configuration for the custom IBGE LULC workflow.

Keep all user-tunable hyperparameters in this file. Implementation modules
should read these values instead of defining local training/model defaults.
"""

input_polygons = "IBGE_method/own_LULC/extra_data/Classes_Uso_Solo.gpkg"
input_ortho = "/home/kaue/data/landslide/feb26/Ortho_4_GNSS-AAT_16cm.tif"


class_definitions = {
    1: {"name": "artif", "ibge_land_use_note": 10.0},
    2: {"name": "descob", "ibge_land_use_note": 5.0},
    3: {"name": "corpo_agua", "ibge_land_use_note": 0.0},
    4: {"name": "veg_campestre", "ibge_land_use_note": 2.0},
    5: {"name": "veg_florestal", "ibge_land_use_note": 1.0},
}


feature_sets = {
    "rgb": {
        "channels": ["red", "green", "blue"],
    },
    "rgb_indices": {
        "channels": [
            "red",
            "green",
            "blue",
            "hue",
            "saturation",
            "value",
            "brightness",
            "excess_green",
            "local_texture",
        ],
    },
}


split_constraints = {
    "strategy": "stratified_spatial_blocks",
    "max_seed_attempts": 400,
    "require_all_classes_per_split": True,
    "min_val_test_pixels_per_class_cap": 20,
    "min_val_test_class_fraction": 0.05,
}


sampler = {
    "strategy": "class_balanced_weighted",
    "rare_class_power": 1.0,
    "max_weight": 20.0,
}


ensemble = {
    "enabled": True,
    "strategy": "probability_average",
    "voter_policy": "diverse_top_models",
    "min_val_macro_iou": 0.98,
    "max_models": 5,
    "exclude_smoke_runs": True,
    "lulc_filename": "lulc_custom_ensemble_1m.tif",
    "probabilities_filename": "lulc_custom_ensemble_probabilities_1m.tif",
    "agreement_filename": "lulc_custom_ensemble_agreement_1m.tif",
    "confidence_filename": "lulc_custom_ensemble_confidence_1m.tif",
    "margin_filename": "lulc_custom_ensemble_margin_1m.tif",
    "entropy_filename": "lulc_custom_ensemble_entropy_1m.tif",
    "results_json_filename": "ensemble_results.json",
    "results_csv_filename": "ensemble_results.csv",
    "low_agreement_threshold": 0.6,
    "low_margin_threshold": 0.2,
    "high_entropy_threshold": 1.0,
}


selection_metric = "macro_iou"
active_experiment = "stage2_1m_baseline"


experiment_grid = {
    "stage1_3m_sanity": {
        "resolution": 3.0,
        "tile_size": 64,
        "stride": 64,
        "inference_window_size": 128,
        "inference_overlap": 32,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "resnet18"},
        "loss": {"name": "weighted_ce_dice"},
        "seeds": [42],
    },
    "stage2_1m_baseline": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "resnet18"},
        "loss": {"name": "weighted_ce_dice"},
        "seeds": [42],
    },
    "stage3_unet_resnet18_focal_dice": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "resnet18"},
        "loss": {"name": "focal_dice"},
        "seeds": [42],
    },
    "stage3_unet_resnet34_weighted_ce_lovasz": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "resnet34"},
        "loss": {"name": "weighted_ce_lovasz"},
        "seeds": [42],
    },
    "stage3_unetplusplus_resnet18_focal_lovasz": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unetplusplus", "encoder": "resnet18"},
        "loss": {"name": "focal_lovasz"},
        "seeds": [42],
    },
    "stage3_deeplabv3plus_resnet18_focal_dice": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "deeplabv3plus", "encoder": "resnet18"},
        "loss": {"name": "focal_dice"},
        "seeds": [42],
    },
    "stage3_fpn_resnet34_weighted_ce_lovasz": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "fpn", "encoder": "resnet34"},
        "loss": {"name": "weighted_ce_lovasz"},
        "seeds": [42],
    },
    "stage3_unet_mit_b0_focal_lovasz": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "mit_b0"},
        "loss": {"name": "focal_lovasz"},
        "seeds": [42],
    },
    "stage4_rgb_indices_template": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb_indices",
        "model": {"architecture": "unet", "encoder": "resnet18"},
        "loss": {"name": "focal_lovasz"},
        "seeds": [42],
    },
    "stage4_seed_robustness_template": {
        "resolution": 1.0,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "resnet18"},
        "loss": {"name": "focal_lovasz"},
        "seeds": [42, 1337, 2026],
    },
    "fullres_unetplusplus_resnet18_focal_lovasz_rgb_indices": {
        "resolution": 0.16,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb_indices",
        "model": {"architecture": "unetplusplus", "encoder": "resnet18"},
        "loss": {"name": "focal_lovasz"},
        "seeds": [42],
    },
    "fullres_deeplabv3plus_resnet18_focal_dice_rgb": {
        "resolution": 0.16,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "deeplabv3plus", "encoder": "resnet18"},
        "loss": {"name": "focal_dice"},
        "seeds": [42],
    },
    "fullres_unet_resnet34_weighted_ce_lovasz_rgb": {
        "resolution": 0.16,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "resnet34"},
        "loss": {"name": "weighted_ce_lovasz"},
        "seeds": [42],
    },
    "fullres_unet_mit_b0_focal_lovasz_rgb": {
        "resolution": 0.16,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "unet", "encoder": "mit_b0"},
        "loss": {"name": "focal_lovasz"},
        "seeds": [42],
    },
    "fullres_fpn_resnet34_weighted_ce_lovasz_rgb": {
        "resolution": 0.16,
        "tile_size": 192,
        "stride": 96,
        "inference_window_size": 256,
        "inference_overlap": 64,
        "feature_set": "rgb",
        "model": {"architecture": "fpn", "encoder": "resnet34"},
        "loss": {"name": "weighted_ce_lovasz"},
        "seeds": [42],
    },
}


lulc_params = {
    "class_text_field": "Classe",
    "class_value_field": "Class_num",
    "output_resolution": 1.0,
    "output_folderpath": "IBGE_method/own_LULC/outputs",
    "output_nodata": 0,
    "ignore_index": 255,
    "lulc_filename": "lulc_custom_1m.tif",
    "probabilities_filename": "lulc_custom_probabilities_1m.tif",
    "metrics_filename": "lulc_training_metrics.json",
    "class_distribution_filename": "lulc_class_distribution.json",
    "metadata_filename": "lulc_model_metadata.json",
    "model_filename": "best_lulc_model.pth",
    "resampled_rgb_filename": "resampled_rgb_1m.tif",
    "training_labels_filename": "training_labels_1m.tif",
    "rasterize_all_touched": False,
    "use_alpha_valid_mask": True,
    "feature_set": "rgb",
    "tile_size": 192,
    "stride": 96,
    "spatial_block_size": 1,
    "min_labeled_pixels_per_tile": 1,
    "train_percentage": 0.5,
    "validation_percentage": 0.35,
    "test_percentage": 0.15,
    "random_seed": 42,
    "selection_metric": selection_metric,
    "model": {
        "architecture": "unet",
        "encoder": "resnet18",
        "encoder_weights": "imagenet",
        "input_channels": 3,
        "output_classes": 5,
    },
    "loss": {
        "name": "weighted_ce_dice",
        "cross_entropy_weight": 1.0,
        "dice_weight": 0.5,
        "focal_weight": 1.0,
        "focal_gamma": 2.0,
        "lovasz_weight": 0.5,
    },
    "training": {
        "epochs": 100,
        "batch_size": 8,
        "learning_rate": 0.0003,
        "weight_decay": 0.0001,
        "optimizer": "adamw",
        "scheduler": "cosine",
        "class_weight_strategy": "inverse_frequency",
        "early_stopping_patience": 100,
        "num_workers": 0,
        "use_cuda": True,
        "save_best_metric": selection_metric,
    },
    "augmentation": {
        "flip_probability": 0.5,
        "rotate90": True,
        "brightness": 0.08,
        "contrast": 0.12,
        "blur_enabled": False,
        "blur_kernel_size": 3,
        "noise_enabled": False,
        "noise_std": 0.01,
    },
    "inference": {
        "window_size": 256,
        "overlap": 64,
        "batch_size": 8,
        "use_cuda": True,
    },
    "postprocessing": {
        "smoothing_enabled": False,
        "smoothing_sigma": 0.75,
        "minimum_mapping_confidence": 0.0,
    },
    "smoke_test": {
        "epochs": 2,
        "max_train_tiles": 8,
        "max_eval_tiles": 4,
    },
}
